### ISSUE TITLE
React errors from prisma service?

### ISSUE THREAD

**Issue by kleydon** [CaptainChemist/blog-prisma2#11]
Hi @CaptainChemist ,

Thanks your helpful tutorial! In particular, it helped me to _finally_ understand how to set up docker-compose, docker files and a .env file (after much scouring the web).

I am puzzled by something, though.

When I run the demo (staging branch), the output from `npm run start` repeatedly shows:

```
prisma      | React will try to recreate this component tree from scratch using the error boundary you provided, App.
prisma      | The above error occurred in the <DevComponent> component:
prisma      |     in DevComponent (created by Context.Consumer)
prisma      |     in Unknown
prisma      |     in App
```

Do you happen to know what this is about? I've tried to find reference to this error on the web, but no luck so far...

**Comment by CaptainChemist** [comment]
Hey @kleydon! 
I see this too. I know that it is coming from the Prisma Studio website but I have no idea why it is occurring and I haven't been able to track it down either. I just made a post over at Prisma Studio, hopefully we will hear something back.  

https://github.com/prisma/studio/issues/134

**Comment by CaptainChemist** [comment]
Closing this because the latest prisma studio from my tests, does not constantly spam this error anymore.
