### ISSUE TITLE
No Tables in Database

### ISSUE THREAD

**Issue by piesrtasty** [CaptainChemist/blog-prisma2#15]
Hello! I followed along with the tutorial and deployed to Zeit however my graphql server is returning the following when attempting to connect to the RDS MySQL instance. Should the deployment take care of creating the tables in the DB or do I need to explicitly do that? I didn't see that mentioned anywhere in the tutorial. However this does work locally.
```
commons.84d14b3ba26b522ce974.js:1 Uncaught (in promise) Error: GraphQL error: Error in Photon: 
Error: Reason: Error in connector: Error querying the database: MySqlError { ERROR 1146 (42S02): Table 'prisma.User' doesn't exist }
```

**Comment by CaptainChemist** [comment]
Hey @lukehamilton - right now the `prismastudio` should be creating the tables for you. Often stopping and starting the containers when you get this error should do the trick. 

To seed the database in a docker environment, the prismastudio docker container runs prisma2 dev which performs the migration. You can also do the same thing without the prisma studio by running prisma2 lift save and prisma2 lift up to first create a migration and then to apply the migration.

**Comment by CaptainChemist** [comment]
I'm closing this issue for now because prisma now uses the migrate commands. After starting the docker cluster, running `npm run migrate` will plan and then execute a migration against the mysql database.
