### ISSUE TITLE
Next + Docker + HMR

### ISSUE THREAD

**Issue by Ciberusps** [CaptainChemist/blog-prisma2#5]
Hi, I cloned repo -> checkout to `now-serverless` branch.
All works perfectly in `npm run start` except nextjs hot reloading.
I'm not experienced with docker enough is this a bug?
OS: windows

**Comment by CaptainChemist** [comment]
Hi there! Thank you so much for reporting this issue. I think I figured out the problem. If you make your `frontend/next.config.js` look like this it will fix the issue for you:

```
module.exports = withCSS({
  target: 'serverless',
  env: {
    BACKEND_URL: process.env.BACKEND_URL
  },
  webpackDevMiddleware: (config) => {
    config.watchOptions = {
      poll: 1000, 
      aggregateTimeout: 300, 
    };
    return config;
  }
});

```

The trick is adding the `webpackDevMiddleware` block.

**Comment by CaptainChemist** [comment]
This works on my end so I am going to close this, but please re-open if you are having troubles.
